### ISSUE TITLE
about weights

### ISSUE THREAD

**Issue by backyardknights** [HengLan/SMOT#1]
Your work gives me great inspiration, but I have encountered some troubles when trying to implement the algorithm.I cannot find the file weights/grit_b_densecap_objectdet.pth loaded in grit_roi_heads.py, and the file models/CH_FPN_1x.pth required by BYTE_BENSMOT_FPN.yaml. Are they not uploaded to GitHub? If possible, could you send me the related files?

**Comment by Nathan-Li123** [comment]
Thanks for your attention. The two weights files you mentioned can be downloaded from here: https://mailsucasaccn-my.sharepoint.com/:f:/g/personal/liyunhao23_mails_ucas_ac_cn/EhcMubyTKB1OqNchDySUtQABL9fbALawt3KVbYNpd9GLnA?e=SLeGgI

**Comment by backyardknights** [comment]
Thanks a lot for your timely and generous help.
