### ISSUE TITLE
Error named ”No such file or directory: 'datasets/bensmot/annotations/train_vu.json’ “

### ISSUE THREAD

**Issue by loseevaya** [HengLan/SMOT#3]
Thank you so much for providing a new direction for the MOT community!
When trying to run your code, I processed the BenSMOT dataset as the section "Dataset preparation" listed, and when i run the code:
`CUDA_VISIBLE_DEVICES=0,1,2,3 python train_net.py --num-gpus 4 --config-file configs/BYTE_BENSMOT_FPN.yaml`
i meet an error:   `No such file or directory: 'datasets/bensmot/annotations/train_vu.json'`

I only got train.json and test.json in the annotations folder after run `tools/convert_bensmot2coco.py`. And i noticed that your had deleted the code about writing files in seqmaps folder, so i didn't get the test.txt in my seqmaps folder.

Looking forward to your reply! Thanks!

**Comment by Nathan-Li123** [comment]
Please change the corresponding path in smoter/data/smoter_dataset_dataloader.py and smoter/data/datasets/bensmot.py. We will fix this problem in later updates.
